/*
* Daniel Ryaboshapka
* Coding Problems 
* February 2nd 2019
*
* Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous 
* 	two terms. By starting with 1 and 2, the first 10 terms will be:
*
*     	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* 	By considering the terms in the Fibonacci sequence whose values do not exceed 
* 	four million, find the sum of the even-valued terms.
*
* LANGUAGE CHOSEN: C 
* 
*
* Time Designing: 2 minutes
* Time Coding: 7 minutes
* Time Documenting: 7 minutes
* Total Time Spent on Problem: 16 minutes
*
* Thoughts on this problem: *BRUTE FORCE APPROACH* 
* 	I knew pretty quickly that a Fibonnaci sequence entailed
* 	recursion, so all I did was check if the current number is divisible by 2 then 
* 	added it to the total. 
* 
* Post Coding Discussion: If I come back to this problem to solve it more elegantly,
* 	looking at some solutions online I came across the closed-form formula of the 
* 	Fibonacci sequence: 
*					
*				Fn = ((F)^n - (-F)^-n)/sqrt(5)
*
*			F: Golden Ratio
*	
*	Observing the Fibonnaci sequence, pretty soon one can realize that the even terms
* 	exist once every 3 iterations starting at 2. Following the stackexchange post 
* 	https://mathematica.stackexchange.com/questions/37266/even-fibonacci-numbers
* 	we can find a very elegant solution that involves manipulating the summation 
* 	and using properties of geometric series to find our answer without computational
* 	power. 
*/

#include <stdio.h>

int evenFibonacci(int curr, int prev, int total)
{
	int even = curr % 2;
	if (curr > 4000000){
		return total;
	}
	if (even == 0){
		total += curr;
	}
	int temp = curr + prev;
	prev = curr; 
	//printf("%d\n",curr ); Debugging purposes
	return evenFibonacci(temp, prev, total);
}


int main(int argc, char const *argv[])
{
	(void) argc;
	(void) argv; 

	int answer = evenFibonacci(1,1,0);
	printf("The answer to Problem 2 is %d\n", answer);
	return 0;
}